### ISSUE TITLE
【質問】Trading Two Shares at One Time

### ISSUE THREAD

**Issue by nobuodesu** [kabucom/kabusapi#79]
When I place two leave orders, can I designate condition that  one trading is for the other's trading, each other.
For example, done of order on share A is for the done condition for order on share B.
Also, done of order on share B is for the done condition for order on share A.
Can I do such conditions?

**Comment by yasuyuki-nakazawa** [comment]
It is possible to place the requested order by specifying the execution condition "relay-order" from the website or kabu Station, but it is not supported as the execution condition of the API.
Regarding the addition of execution conditions, we plan to consider adding them one by one in the future.

**Comment by nobuodesu** [comment]
Nakazawa san,
Thank you for the comment.
Can I request that the API include order method with such condition?z
It seems important to diversify trading strategies.

**Comment by yasuyuki-nakazawa** [comment]
Currently, it is not possible to specify the listed automatic trading.

Since it is possible to obtain the status of various orders, so it is also possible to place the expected conditional orders by building the logic yourself. 

However, I think there are performance concerns as you need to constantly monitor order status.
So we are considering an interface that allows you to check order execution status and possition status at high speed using various filters.
By using these new functions, I think it is possible to make diversification faster and more convenient in the future.

**Comment by nobuodesu** [comment]
Understood the situation.
Thanks very much for your comments.
